on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: istemi/multiple-env-in-secrets@v3
      with:
        who-to-greet: '${{ secrets.TEST_ENV }}'
    # Use the output from the `hello` step
    - name: Get variables
      run: |
        export REACT_APP_DATA_DOG_CLIENT_APPLICATION_ID="11123"
        echo ${{ steps.hello.outputs.time }} | wc -l
        ./run.sh
