on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: istemi/multiple-env-in-secrets@v3
      with:
        who-to-greet: '${{ secrets.TEST_ENV }}'
    # Use the output from the `hello` step
    - name: Get variables
      run: |
        ${{ steps.hello.outputs.time }}
        ./run.sh
