on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello multi secrets
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get multiple secrets from GitHub Secrets
      id: hello
      uses: istemi/multiple-env-in-secrets@v4
      with:
        who-to-greet: '${{ secrets.TEST_ENV }}'
    # Use the output from the `hello` step
    - name: Get variables
      run: |
        echo ${{ steps.hello.outputs.time }} | wc -l
        ./run.sh
